name = "PrettyChairmarks"
uuid = "aafa11c5-44f9-44a1-b829-427e6ce1ffc2"
authors = ["Marco Lombardi <marco.lombardi@gmail.com>"]
version = "1.0.0"

[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Chairmarks = "1.2.0"
Printf = "1.6.0"
Statistics = "1.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
